### PR TITLE
Minor fixes

### PR DESCRIPTION
**Pull request by ncorgan**

### CODE REVIEW

**Comment by Grazfather** [comment]
Ah I had most these changes locally but never pushed them. Thanks!

**Comment by Grazfather** [comment]
I just added you as a collaborator for the project, so you can go ahead and push changes directly to my tree. I haven't had a lot of time myself to work on this, unfortunately.

**Comment by ncorgan** [comment]
Was definitely surprised to see this. Awesome, thanks.

On Mon, Aug 5, 2013 at 5:07 PM, Grazfather notifications@github.com wrote:

> I just added you as a collaborator for the project, so you can go ahead
> and push changes directly to my tree. I haven't had a lot of time myself to
> work on this, unfortunately.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/Grazfather/pokehack/pull/6#issuecomment-22149978
> .

## 

Nicholas Corgan

**Comment by Grazfather** [comment]
No problem. Let's just use feature branches and stuff when appropriate to
keep master working. We can just ffwd to avoid branches in the future
(since we probably won't both be working at the same time).

One thing I do want to do is re-abstract it so that the save parser and the
pokemon parser are full separate. I'd also like to convert the console tool
to c++ to use the cpp tools and so we can delete the duplicate code.

On Tue, Aug 6, 2013 at 8:22 AM, Nicholas Corgan notifications@github.comwrote:

> Was definitely surprised to see this. Awesome, thanks.
> 
> On Mon, Aug 5, 2013 at 5:07 PM, Grazfather notifications@github.com
> wrote:
> 
> > I just added you as a collaborator for the project, so you can go ahead
> > and push changes directly to my tree. I haven't had a lot of time myself
> > to
> > work on this, unfortunately.
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/Grazfather/pokehack/pull/6#issuecomment-22149978>
> > .
> 
> ## 
> 
> Nicholas Corgan
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/Grazfather/pokehack/pull/6#issuecomment-22187164
> .

## 

Thanks,

Graziano

**Comment by ncorgan** [comment]
Assuming we're thinking along the same lines, a PokemonParser class would
be quite useful. It would be great to abstract out the use of
belt_pokemon_t, etc into one data structure; it would get rid of the code
duplication, and it would make the library more intuitive to use. My
schedule's about to clear up significantly, so I can get a start on that in
the next few days.

On Tue, Aug 6, 2013 at 10:44 AM, Grazfather notifications@github.comwrote:

> No problem. Let's just use feature branches and stuff when appropriate to
> keep master working. We can just ffwd to avoid branches in the future
> (since we probably won't both be working at the same time).
> 
> One thing I do want to do is re-abstract it so that the save parser and
> the
> pokemon parser are full separate. I'd also like to convert the console
> tool
> to c++ to use the cpp tools and so we can delete the duplicate code.
> 
> On Tue, Aug 6, 2013 at 8:22 AM, Nicholas Corgan notifications@github.comwrote:
> 
> > Was definitely surprised to see this. Awesome, thanks.
> > 
> > On Mon, Aug 5, 2013 at 5:07 PM, Grazfather notifications@github.com
> > wrote:
> > 
> > > I just added you as a collaborator for the project, so you can go
> > > ahead
> > > and push changes directly to my tree. I haven't had a lot of time
> > > myself
> > > to
> > > work on this, unfortunately.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub<
> > > https://github.com/Grazfather/pokehack/pull/6#issuecomment-22149978>
> > > .
> > 
> > ## 
> > 
> > Nicholas Corgan
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/Grazfather/pokehack/pull/6#issuecomment-22187164>
> > .
> 
> ## 
> 
> Thanks,
> 
> Graziano
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/Grazfather/pokehack/pull/6#issuecomment-22197132
> .

## 

Nicholas Corgan

**Comment by Grazfather** [comment]
Yeah exactly. A saveparser could have a member that returns an instance of
a pokemon. Right now I keep all the data in place, including decrypting and
editing. The issue with this is we need to track whether or not the pokemon
data has been decrypted. If we instead copy out the pokemon data from the
savedata (i.e. Pokemon a = new Pokemon(saveparser.getBeltPokemon(1));) and
we decrypt it in the constructor (or at least keep track of whether or not
it's decrypted) we can have multiple clients copying and editing pokemon
data, we just need to re-encrypt it before we put it into a belt or box
slot in the pokemon save file. This allows us to copy belt pokemon to the
box, and vice versa, but box to belt is a bit more complication since we
would need to generate the extra 20 bytes of information (but I am pretty
sure if it was all wrong it wouldn't matter as long as we put the pokemon
in the box to have the extra data regenerated by the game.)

This also makes copying pokemon simpler, as well as changing the
personality to make shinies and such.

If you'd like, we could organize some point to discuss the actual design,
but it does look like we are on the same page.

On Thu, Aug 8, 2013 at 1:36 PM, Nicholas Corgan notifications@github.comwrote:

> Assuming we're thinking along the same lines, a PokemonParser class would
> be quite useful. It would be great to abstract out the use of
> belt_pokemon_t, etc into one data structure; it would get rid of the code
> duplication, and it would make the library more intuitive to use. My
> schedule's about to clear up significantly, so I can get a start on that
> in
> the next few days.
> 
> On Tue, Aug 6, 2013 at 10:44 AM, Grazfather notifications@github.comwrote:
> 
> > No problem. Let's just use feature branches and stuff when appropriate
> > to
> > keep master working. We can just ffwd to avoid branches in the future
> > (since we probably won't both be working at the same time).
> > 
> > One thing I do want to do is re-abstract it so that the save parser and
> > the
> > pokemon parser are full separate. I'd also like to convert the console
> > tool
> > to c++ to use the cpp tools and so we can delete the duplicate code.
> > 
> > On Tue, Aug 6, 2013 at 8:22 AM, Nicholas Corgan <
> > notifications@github.com>wrote:
> > 
> > > Was definitely surprised to see this. Awesome, thanks.
> > > 
> > > On Mon, Aug 5, 2013 at 5:07 PM, Grazfather notifications@github.com
> > > wrote:
> > > 
> > > > I just added you as a collaborator for the project, so you can go
> > > > ahead
> > > > and push changes directly to my tree. I haven't had a lot of time
> > > > myself
> > > > to
> > > > work on this, unfortunately.
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub<
> > > > https://github.com/Grazfather/pokehack/pull/6#issuecomment-22149978>
> > > > .
> > > 
> > > ## 
> > > 
> > > Nicholas Corgan
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub<
> > > https://github.com/Grazfather/pokehack/pull/6#issuecomment-22187164>
> > > .
> > 
> > ## 
> > 
> > Thanks,
> > 
> > Graziano
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/Grazfather/pokehack/pull/6#issuecomment-22197132>
> > .
> 
> ## 
> 
> Nicholas Corgan
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/Grazfather/pokehack/pull/6#issuecomment-22353549
> .

## 

Thanks,

Graziano

**Pull request merged**
